# Numpy

In [3]:
import numpy as np

In [5]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [6]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [7]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
list_of_lists=[[78,90,78],[56.90,67,80]]
np.array(list_of_lists)

array([[78. , 90. , 78. ],
       [56.9, 67. , 80. ]])

In [11]:
np.arange(5,65)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64])

In [56]:
np.arange(2,40,6)

array([ 2,  8, 14, 20, 26, 32, 38])

In [59]:
np.zeros(1000)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [61]:
np.zeros(500,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [62]:
np.zeros((7,15))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [64]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [65]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [66]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [70]:
np.linspace(2,4,8)

array([2.        , 2.28571429, 2.57142857, 2.85714286, 3.14285714,
       3.42857143, 3.71428571, 4.        ])

In [71]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [75]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [78]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [80]:
np.random.rand(2,4)

array([[0.38482447, 0.49921604, 0.50834631, 0.01863155],
       [0.50512752, 0.02602998, 0.61686366, 0.83776812]])

In [163]:
arr=np.random.rand(2,4)
arr

array([[0.6532346 , 0.4475519 , 0.17976821, 0.02476964],
       [0.12741006, 0.28946384, 0.48299313, 0.78220471]])

In [169]:
np.random.randint(2,8)

3

In [165]:
np.random.randint(21,57,99)

array([38, 35, 25, 30, 42, 36, 23, 30, 29, 50, 47, 48, 30, 49, 29, 32, 36,
       53, 43, 51, 21, 32, 24, 21, 43, 25, 43, 40, 44, 24, 54, 33, 31, 24,
       50, 33, 36, 50, 54, 56, 46, 35, 29, 29, 22, 26, 55, 27, 39, 28, 28,
       48, 53, 24, 45, 56, 49, 21, 50, 44, 33, 27, 40, 30, 28, 37, 51, 24,
       44, 34, 48, 41, 29, 29, 37, 26, 29, 28, 42, 56, 54, 36, 51, 52, 25,
       29, 56, 23, 24, 45, 35, 26, 28, 45, 21, 39, 25, 27, 41])

In [166]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [98]:
rand_array=np.random.randint(0,100,20)
rand_array

array([16, 14,  9, 16, 18, 44, 40, 23, 48, 50, 10, 70, 69, 52, 32, 67, 60,
       79, 44, 11])

In [111]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [100]:
rand_array.min()

9

In [101]:
rand_array.argmin()

2

In [103]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [104]:
sample_array.shape

(30,)

In [105]:
sample_array.dtype

dtype('int32')

In [106]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [107]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [114]:
a=np.random.rand(2,3)
a

array([[0.07056645, 0.72553541, 0.73184301],
       [0.38583808, 0.6520272 , 0.69452253]])

In [115]:
a.T

array([[0.07056645, 0.38583808],
       [0.72553541, 0.6520272 ],
       [0.73184301, 0.69452253]])

In [118]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [120]:
sample_array[8]

18

In [121]:
sample_array[2:5]

array([12, 13, 14])

In [122]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [123]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [124]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [125]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [126]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# Two-Dimensional Array

In [127]:
import numpy as np

In [128]:
sample_matrix=np.array(([50,20,1,30],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 30],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [136]:
sample_matrix[0][2]

1

In [133]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [131]:
sample_matrix[2]

array([56, 76, 24,  7])

# Custom Indexing

In [137]:
sample_matrix=np.array(([30,10,1,23],[24,23,21,33],[6,76,24,7]))
sample_matrix

array([[30, 10,  1, 23],
       [24, 23, 21, 33],
       [ 6, 76, 24,  7]])

In [138]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

# Selection Techniques

In [142]:
sample_array=np.arange(10)
sample_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
sample_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
sample_array+sample_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [146]:
np.exp(sample_array)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [147]:
np.sqrt(sample_array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [148]:
np.log(sample_array)

C:\Users\akanksha\AppData\Local\Temp\ipykernel_10412\988743405.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(sample_array)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [149]:
np.max(sample_array)

9

In [150]:
np.min(sample_array)

0

In [151]:
np.argmin(sample_array)

0

In [152]:
np.square(sample_array)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [153]:
np.std(sample_array)

2.8722813232690143

In [154]:
np.var(sample_array)

8.25

In [155]:
np.mean(sample_array)

4.5

In [156]:
array=np.random.randn(3,6)
array

array([[-1.77310016,  0.96116679,  1.03753515, -0.82258622,  1.41746981,
         1.91417441],
       [-1.18397976, -1.18826254, -0.14347439,  1.09127233,  1.04752625,
         1.31138742],
       [-0.56994786,  0.22428198,  0.24483553,  0.4685358 , -0.75711739,
         0.99276794]])

In [161]:
np.round(array,decimals=1)

array([[-1.8,  1. ,  1. , -0.8,  1.4,  1.9],
       [-1.2, -1.2, -0.1,  1.1,  1. ,  1.3],
       [-0.6,  0.2,  0.2,  0.5, -0.8,  1. ]])

In [162]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

# Pandas

In [170]:
import numpy as np
import pandas as pd

In [172]:
labels=['w','x','y','z']
sample_list=[10,20,30,40]
array=np.array([1,2,3,4])
dict={'w':10,'x':20,'y':30,'z':40}


In [174]:
pd.Series(data=sample_list)

0    10
1    20
2    30
3    40
dtype: int64

In [176]:
pd.Series(data=sample_list,index=labels)

w    10
x    20
y    30
z    40
dtype: int64

In [178]:
pd.Series(array,labels)

w    1
x    2
y    3
z    4
dtype: int32

In [179]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

# Pandas DataFrame and  Indexing

In [182]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [184]:
sports1['football']

2

In [185]:
sports2=pd.Series([11,21,31,41],index=['cricket','football','basketball','golf'])
sports2

cricket       11
football      21
basketball    31
golf          41
dtype: int64

In [186]:
sports1+sports2

cricket       12
football      23
basketball    34
golf          45
dtype: int64

In [205]:
import numpy as np
import pandas as pd

In [223]:
df1=pd.DataFrame(np.random.randn(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.040203  1.229161  1.239078  0.751950 -0.071578
B -0.241893  0.530958  0.928414 -1.568794  1.132524
C -0.623602  0.486505  1.625043  2.211577  0.577373
D  0.720798 -0.573392 -0.533650 -0.114159 -0.637645
E -0.256173 -0.781493  1.686724  0.247962  1.681295
F -0.968218 -1.030390  2.746201  2.029023 -1.160787
G  1.396671 -0.513608  0.548807  3.390435 -0.148877
H -1.638375  0.600417  1.122696  0.421059  1.526428

In [224]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.040203  1.229161  1.239078  0.751950 -0.071578  1.269364
B -0.241893  0.530958  0.928414 -1.568794  1.132524  0.289065
C -0.623602  0.486505  1.625043  2.211577  0.577373 -0.137097
D  0.720798 -0.573392 -0.533650 -0.114159 -0.637645  0.147406
E -0.256173 -0.781493  1.686724  0.247962  1.681295 -1.037667
F -0.968218 -1.030390  2.746201  2.029023 -1.160787 -1.998608
G  1.396671 -0.513608  0.548807  3.390435 -0.148877  0.883063
H -1.638375  0.600417  1.122696  0.421059  1.526428 -1.037957

In [221]:
df1.drop("Score5", axis=1)

Score1    Score2    Score3    Score4    Score6
A -0.019669 -1.334815  0.382498  0.856773 -1.354484
B -0.635288 -0.175213 -0.909936  0.586846 -0.810501
C -0.533549  1.113054 -0.036016  0.739076  0.579505
D -0.174995  0.114756 -0.200422 -1.548135 -0.060239
E -0.402603 -0.687883  0.883679 -0.448674 -1.090486
F -0.695217  0.195236 -0.167607 -0.327660 -0.499981
G  1.277082  0.342205  0.786711  0.887877  1.619287
H -1.096136 -0.705513 -1.126278 -0.569558 -1.801649

In [225]:
df1.drop('E')

Score1    Score2    Score3    Score4    Score5    Score6
A  0.040203  1.229161  1.239078  0.751950 -0.071578  1.269364
B -0.241893  0.530958  0.928414 -1.568794  1.132524  0.289065
C -0.623602  0.486505  1.625043  2.211577  0.577373 -0.137097
D  0.720798 -0.573392 -0.533650 -0.114159 -0.637645  0.147406
F -0.968218 -1.030390  2.746201  2.029023 -1.160787 -1.998608
G  1.396671 -0.513608  0.548807  3.390435 -0.148877  0.883063
H -1.638375  0.600417  1.122696  0.421059  1.526428 -1.037957

In [226]:
df1.drop("Score1", axis=1)

Score2    Score3    Score4    Score5    Score6
A  1.229161  1.239078  0.751950 -0.071578  1.269364
B  0.530958  0.928414 -1.568794  1.132524  0.289065
C  0.486505  1.625043  2.211577  0.577373 -0.137097
D -0.573392 -0.533650 -0.114159 -0.637645  0.147406
E -0.781493  1.686724  0.247962  1.681295 -1.037667
F -1.030390  2.746201  2.029023 -1.160787 -1.998608
G -0.513608  0.548807  3.390435 -0.148877  0.883063
H  0.600417  1.122696  0.421059  1.526428 -1.037957

In [227]:
df1.drop("A", axis=0)

Score1    Score2    Score3    Score4    Score5    Score6
B -0.241893  0.530958  0.928414 -1.568794  1.132524  0.289065
C -0.623602  0.486505  1.625043  2.211577  0.577373 -0.137097
D  0.720798 -0.573392 -0.533650 -0.114159 -0.637645  0.147406
E -0.256173 -0.781493  1.686724  0.247962  1.681295 -1.037667
F -0.968218 -1.030390  2.746201  2.029023 -1.160787 -1.998608
G  1.396671 -0.513608  0.548807  3.390435 -0.148877  0.883063
H -1.638375  0.600417  1.122696  0.421059  1.526428 -1.037957

In [229]:
df1.drop(["Score1","Score2"], axis=1)

Score3    Score4    Score5    Score6
A  1.239078  0.751950 -0.071578  1.269364
B  0.928414 -1.568794  1.132524  0.289065
C  1.625043  2.211577  0.577373 -0.137097
D -0.533650 -0.114159 -0.637645  0.147406
E  1.686724  0.247962  1.681295 -1.037667
F  2.746201  2.029023 -1.160787 -1.998608
G  0.548807  3.390435 -0.148877  0.883063
H  1.122696  0.421059  1.526428 -1.037957

In [230]:
df2={'ID':['101','102','103','107','176'],'Name':['john','Mercy','Akash','Kavin','Lally'],'Profit':[20,30,40,50,60]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   john      20
1  102  Mercy      30
2  103  Akash      40
3  107  Kavin      50
4  176  Lally      60

In [231]:
df.drop("ID",axis=1)

Name  Profit
0   john      20
1  Mercy      30
2  Akash      40
3  Kavin      50
4  Lally      60

In [232]:
df.drop(2)

ID   Name  Profit
0  101   john      20
1  102  Mercy      30
3  107  Kavin      50
4  176  Lally      60

In [233]:
df[['Name','Profit']]

Name  Profit
0   john      20
1  Mercy      30
2  Akash      40
3  Kavin      50
4  Lally      60

In [234]:
df[['Name','ID']]

Name   ID
0   john  101
1  Mercy  102
2  Akash  103
3  Kavin  107
4  Lally  176

# Reading an Excel File

In [235]:
import numpy as np
import pandas as pd

In [237]:
df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/HHE_June5/main/CardioGoodFitness-1.csv")

In [238]:
df.head()

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   TM195   18    Male         14        Single      3        4   29562    112
1   TM195   19    Male         15        Single      2        3   31836     75
2   TM195   19  Female         14     Partnered      4        3   30699     66
3   TM195   19    Male         12        Single      3        3   32973     85
4   TM195   20    Male         13     Partnered      4        2   35247     47

In [239]:
df.head(10)

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   TM195   18    Male         14        Single      3        4   29562    112
1   TM195   19    Male         15        Single      2        3   31836     75
2   TM195   19  Female         14     Partnered      4        3   30699     66
3   TM195   19    Male         12        Single      3        3   32973     85
4   TM195   20    Male         13     Partnered      4        2   35247     47
5   TM195   20  Female         14     Partnered      3        3   32973     66
6   TM195   21  Female         14     Partnered      3        3   35247     75
7   TM195   21    Male         13        Single      3        3   32973     85
8   TM195   21    Male         15        Single      5        4   35247    141
9   TM195   21  Female         15     Partnered      2        3   37521     85

In [240]:
df.head(25)

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
0    TM195   18    Male         14        Single      3        4   29562   
1    TM195   19    Male         15        Single      2        3   31836   
2    TM195   19  Female         14     Partnered      4        3   30699   
3    TM195   19    Male         12        Single      3        3   32973   
4    TM195   20    Male         13     Partnered      4        2   35247   
5    TM195   20  Female         14     Partnered      3        3   32973   
6    TM195   21  Female         14     Partnered      3        3   35247   
7    TM195   21    Male         13        Single      3        3   32973   
8    TM195   21    Male         15        Single      5        4   35247   
9    TM195   21  Female         15     Partnered      2        3   37521   
10   TM195   22    Male         14        Single      3        3   36384   
11   TM195   22  Female         14     Partnered      3        2   35247   
12   TM195   22  Female         16        Single      4        3   36384   
13   TM195   22  Female         14        Single      3        3   35247   
14   TM195   23    Male         16     Partnered      3        1   38658   
15   TM195   23    Male         16     Partnered      3        3   40932   
16   TM195   23  Female         14        Single      2        3   34110   
17   TM195   23    Male         16     Partnered      4        3   39795   
18   TM195   23  Female         16        Single      4        3   38658   
19   TM195   23  Female         15     Partnered      2        2   34110   
20   TM195   23    Male         14        Single      4        3   38658   
21   TM195   23    Male         16        Single      4        3   40932   
22   TM195   24  Female         16        Single      4        3   42069   
23   TM195   24  Female         16     Partnered      5        5   44343   
24   TM195   24    Male         14        Single      2        3   45480   

    Miles  
0     112  
1      75  
2      66  
3      85  
4      47  
5      66  
6      75  
7      85  
8     141  
9      85  
10     85  
11     66  
12     75  
13     75  
14     47  
15     75  
16    103  
17     94  
18    113  
19     38  
20    113  
21     94  
22     94  
23    188  
24    113

In [241]:
df.tail()

Product  Age Gender  Education MaritalStatus  Usage  Fitness  Income  \
175   TM798   40   Male         21        Single      6        5   83416   
176   TM798   42   Male         18        Single      5        4   89641   
177   TM798   45   Male         16        Single      5        5   90886   
178   TM798   47   Male         18     Partnered      4        5  104581   
179   TM798   48   Male         18     Partnered      4        5   95508   

     Miles  
175    200  
176    200  
177    160  
178    120  
179    180

In [242]:
df.tail(25)

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
155   TM798   25    Male         18     Partnered      6        5   75946   
156   TM798   25    Male         20     Partnered      4        5   74701   
157   TM798   26  Female         21        Single      4        3   69721   
158   TM798   26    Male         16     Partnered      5        4   64741   
159   TM798   27    Male         16     Partnered      4        5   83416   
160   TM798   27    Male         18        Single      4        3   88396   
161   TM798   27    Male         21     Partnered      4        4   90886   
162   TM798   28  Female         18     Partnered      6        5   92131   
163   TM798   28    Male         18     Partnered      7        5   77191   
164   TM798   28    Male         18        Single      6        5   88396   
165   TM798   29    Male         18        Single      5        5   52290   
166   TM798   29    Male         14     Partnered      7        5   85906   
167   TM798   30  Female         16     Partnered      6        5   90886   
168   TM798   30    Male         18     Partnered      5        4  103336   
169   TM798   30    Male         18     Partnered      5        5   99601   
170   TM798   31    Male         16     Partnered      6        5   89641   
171   TM798   33  Female         18     Partnered      4        5   95866   
172   TM798   34    Male         16        Single      5        5   92131   
173   TM798   35    Male         16     Partnered      4        5   92131   
174   TM798   38    Male         18     Partnered      5        5  104581   
175   TM798   40    Male         21        Single      6        5   83416   
176   TM798   42    Male         18        Single      5        4   89641   
177   TM798   45    Male         16        Single      5        5   90886   
178   TM798   47    Male         18     Partnered      4        5  104581   
179   TM798   48    Male         18     Partnered      4        5   95508   

     Miles  
155    240  
156    170  
157    100  
158    180  
159    160  
160    100  
161    100  
162    180  
163    180  
164    150  
165    180  
166    300  
167    280  
168    160  
169    150  
170    260  
171    200  
172    150  
173    360  
174    150  
175    200  
176    200  
177    160  
178    120  
179    180

In [244]:
df.sample()

Product  Age Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
39   TM195   26   Male         16     Partnered      4        4   44343    132

In [246]:
df.sample(10)

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
178   TM798   47    Male         18     Partnered      4        5  104581   
97    TM498   25  Female         14     Partnered      2        3   45480   
152   TM798   25  Female         18     Partnered      5        5   61006   
130   TM498   35  Female         16        Single      3        2   50028   
113   TM498   30  Female         14        Single      3        3   57987   
13    TM195   22  Female         14        Single      3        3   35247   
138   TM498   45    Male         16     Partnered      2        2   54576   
128   TM498   35  Female         14     Partnered      3        2   52302   
44    TM195   28  Female         14     Partnered      2        3   46617   
168   TM798   30    Male         18     Partnered      5        4  103336   

     Miles  
178    120  
97      85  
152    200  
130     64  
113     74  
13      75  
138     42  
128     53  
44      56  
168    160

In [248]:
df.dtypes

Product          object
Age               int64
Gender           object
Education         int64
MaritalStatus    object
Usage             int64
Fitness           int64
Income            int64
Miles             int64
dtype: object

In [249]:
df.columns

Index(['Product', 'Age', 'Gender', 'Education', 'MaritalStatus', 'Usage',
       'Fitness', 'Income', 'Miles'],
      dtype='object')

In [250]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Product        180 non-null    object
 1   Age            180 non-null    int64 
 2   Gender         180 non-null    object
 3   Education      180 non-null    int64 
 4   MaritalStatus  180 non-null    object
 5   Usage          180 non-null    int64 
 6   Fitness        180 non-null    int64 
 7   Income         180 non-null    int64 
 8   Miles          180 non-null    int64 
dtypes: int64(6), object(3)
memory usage: 12.8+ KB


In [252]:
df.shape

(180, 9)

In [253]:
df.describe()

Age   Education       Usage     Fitness         Income  \
count  180.000000  180.000000  180.000000  180.000000     180.000000   
mean    28.788889   15.572222    3.455556    3.311111   53719.577778   
std      6.943498    1.617055    1.084797    0.958869   16506.684226   
min     18.000000   12.000000    2.000000    1.000000   29562.000000   
25%     24.000000   14.000000    3.000000    3.000000   44058.750000   
50%     26.000000   16.000000    3.000000    3.000000   50596.500000   
75%     33.000000   16.000000    4.000000    4.000000   58668.000000   
max     50.000000   21.000000    7.000000    5.000000  104581.000000   

            Miles  
count  180.000000  
mean   103.194444  
std     51.863605  
min     21.000000  
25%     66.000000  
50%     94.000000  
75%    114.750000  
max    360.000000

In [254]:
import numpy as np
import pandas as pd

In [ ]:
df.